### ISSUE TITLE
Разрушитель чанков in disable

### ISSUE THREAD

**Issue by Serg284** [Kotori316/QuarryPlus#250]
На версии майнкрафт 1.16.5 не работает разрушитель чанков, что делать? Изменение конфигов ничего не меняет

**Comment by Kotori316** [comment]
The config file, `quarryplus-common.toml` contains these lines.
```toml
#Setting of enabling or disabling each machine. True to disable.
[common.machines]
	WorkbenchPlus = false
	QuarryPlus = false
	PumpPlus = false
	ModuleTorch = false
	ExpPump = false
	ModulePump = false
	EnchantMoverFromBook = false
	Placer = false
	MiningwellPlus = true
	AdvancedPump = false
	Replacer = false
	SolidFuelQuarry = false
	ModuleFuel = false
	SpawnerController = false
	ChunkDestroyer = true
	NewQuarry = false
	CreativeGenerator = false
	EnchantMover = false
	ModuleReplacer = false
	ModuleExpPump = true
	MiniQuarry = false
	ModuleRemoveBedrock = false
	MarkerPlus = false
```
Change the line `ChunkDestroyer = true` to `ChunkDestroyer = false` to enable Chunk Destroyer.
